[package]
name = "warp-starwars"
version = "0.1.1"
authors = ["test"]
edition = "2018"

[dependencies]
async-graphql = "2.5"
async-graphql-warp = "2.5"
tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread"] }
warp = "0.3"
http = "0.2"
slab = "0.4.2"
